### PR TITLE
Closes #229 Bug: There are no validation in the 'Deck description' and 'Deck name' fields

### LINKED ISSUE #229: Bug: There are no validation in the 'Deck description' and 'Deck name' fields
JIRA: ORLP-373

Steps to reproduce:
Go to ORLP Home page infolve.com
Sign Up as administrator (admin@gmail.com - login, 11111111 - password
Click to 'Admin deck' tab on the main menu
Click to 'Add new deck' button
Enter more than 50 characters in the 'Deck name' field.
Enter more than 200 characters in the 'Deck description'
Choose category in 'Category' field
Actual result: 
Deck is created with too long deck description and deck name
Error message doesn't appear if admin enter more then 200 characters in the 'Deck description' field 
Error message doesn't appear if admin enter more then 50 characters in the 'Deck name' field

Expected result:
The 'Add' button should be disabled
Should be error: 'Deck description is too long, please enter less than 200 characters'
Should be error: 'Deck name is too long, please enter less than 50 characters'

### PR DESCRIPTION
**Pull request by volodymyrglynka**

### CODE REVIEW

File: src/main/java/com/softserve/academy/spaced/repetition/controller/dto/impl/DeckCreateValidationDTO.java [hunk 1]
```diff
@@ -0,0 +1,26 @@
+package com.softserve.academy.spaced.repetition.controller.dto.impl;
+
+import org.hibernate.validator.constraints.Length;
+
+public class DeckCreateValidationDTO {
+
+    @Length(min = 2, max = 50)
```
Comment (antonbakalets) [inline src/main/java/com/softserve/academy/spaced/repetition/controller/dto/impl/DeckCreateValidationDTO.java]: Length is Hibernate specific. Please replace by javax.validation.constraints.Size.

**Review by antonbakalets — CHANGES_REQUESTED** [review]
Please update the failing DeckServiceTest.java

File: src/main/java/com/softserve/academy/spaced/repetition/controller/dto/impl/DeckCreateValidationDTO.java (hunk 1 above)
Comment (antonbakalets) [reply src/main/java/com/softserve/academy/spaced/repetition/controller/dto/impl/DeckCreateValidationDTO.java]: Please also take into account that according https://javaee.github.io/javaee-spec/javadocs/javax/validation/constraints/Size.html null values are considered valid. Maybe it makes sense to add NotEnmpty or NotBlank from https://javaee.github.io/javaee-spec/javadocs/javax/validation/constraints/package-summary.html

Comment (volodymyrglynka) [reply src/main/java/com/softserve/academy/spaced/repetition/controller/dto/impl/DeckCreateValidationDTO.java]: I've added changes. Please review them.P.S.: there is a mistake in commit description-instead of DeckControllerTest.java should be DeckServiceTest.java.

**Review by antonbakalets — APPROVED** [review]

**Review by OleksandrBartosh — APPROVED** [review]

**Review by OleksandrMazur — APPROVED** [review]

**Review by Maks-Chornyi — APPROVED** [review]
